---
title: "Plot Normalized Counts"
output: html_notebook
---

# WT vs Knockout
## Load normalized count data

```{r}
sampleTable <- read.csv("sample_table.csv")
ko_wt_counts <- 
    read.csv("output/knockout_vs_WT_standard_analysis_normalized_counts.csv")
```

### Reformat data
Now we'll massage the data into a "long" format to make it easier to deal with
in ggplot2.
```{r tidy_data}
library(tibble)
library(tidyr)
library(dplyr)

ko_wt_counts_tbl <- ko_wt_counts %>% 
    as_tibble() %>%
    rename(gene_id = X) %>%
    rename_(.dots=setNames(names(.), gsub("\\.", "-", names(.)))) %>%
    gather(sample_id, count, -gene_id) %>%
    left_join(sampleTable, by = c("sample_id" = "sample_id")) %>%
    mutate(sample_id = as.factor(sample_id)) %>%
    select(-file)
ko_wt_counts_tbl
```

### Summarize replicates
```{r summarize_means}
ko_wt_counts_tbl_means <- ko_wt_counts_tbl %>% 
    group_by(gene_id, genotype) %>% 
    summarize(mean_count = mean(count))
ko_wt_counts_tbl_means
```

```{r spread_summary}
ko_wt_plot_data <- ko_wt_counts_tbl_means %>%
    spread(genotype, mean_count)
ko_wt_plot_data
```

### Plot
```{r plot}
library(ggplot2)
library(scales)

ggplot(ko_wt_plot_data, 
       aes(x=knockout, y=WT)) +
    geom_point(shape=1) + 
    scale_x_continuous(trans=log2_trans(), name="Knockout (mean count)") +
    scale_y_continuous(trans=log2_trans(), name="WT (mean count)") +
    ggtitle("WT vs Knockout Normalized Counts")
```


# Re-expressed vs Knockout
```{r re_vs_ko}

# Load data
ko_re_counts <- 
    read.csv("output/knockout_vs_re-expressed_standard_analysis_normalized_counts.csv")

ko_re_counts_tbl <- ko_re_counts %>% 
    as_tibble() %>%
    rename(gene_id = X) %>%
    rename_(.dots=setNames(names(.), gsub("\\.", "-", names(.)))) %>%
    gather(sample_id, count, -gene_id) %>%
    left_join(sampleTable, by = c("sample_id" = "sample_id")) %>%
    mutate(sample_id = as.factor(sample_id)) %>%
    select(-file)

# Means by genotype
ko_re_counts_tbl_means <- ko_re_counts_tbl %>% 
    group_by(gene_id, genotype) %>% 
    summarize(mean_count = mean(count))

# Spread genotypes per gene
ko_re_plot_data <- ko_re_counts_tbl_means %>%
    spread(genotype, mean_count)

# Plot
ggplot(ko_re_plot_data, 
       aes(x=knockout, y=`re-expressed`)) +
    geom_point(shape=1) + 
    scale_x_continuous(trans=log2_trans(), name="Knockout (mean count)") +
    scale_y_continuous(trans=log2_trans(), name="Re-expressed (mean count)") +
    ggtitle("Re-expressed vs Knockout Normalized Counts")
```


